server:
  port: 8083

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5432/${SPRING_DATASOURCE_DATABASE:notification_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.bankhub.notification.infrastructure.messaging.dto.AccountEventMessage

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

resilience4j:
  retry:
    instances:
      emailRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - org.springframework.mail.MailException
          - java.net.ConnectException


management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health, info, metrics
