server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://keycloak:8080/realms/bankhub/protocol/openid-connect/certs}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/bankhub}

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000" # Frontend React
              - "http://localhost:8089" # BFF
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: account-read-only-route
          uri: http://bank-account-service:8081
          predicates:
            - Path=/api/v1/accounts/{accountId}
            - Method=GET
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                redis-rate-limiter.requestedTokens: 1

        - id: account-activation-route
          uri: http://bank-account-service:8081
          predicates:
            - Path=/api/v1/accounts/activate
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1

        - id: account-dict-route
          uri: http://bank-account-service:8081
          predicates:
            - Path=/api/v1/accounts/dict/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1

        - id: account-service-route
          uri: http://bank-account-service:8081
          predicates:
            - Path=/api/v1/accounts/{accountId}/**, /api/v1/accounts
          filters:
            - AccountStatusGuardrail
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        - id: onboarding-service-route
          uri: http://bank-onboarding-service:8082
          predicates:
            - Path=/api/v1/onboarding/**

        - id: hub-ia-service-route
          uri: http://bank-hub-ia:8084
          predicates:
            - Path=/api/v1/chat/**

        - id: transaction-service-route
          uri: http://bank-transaction-service:8085
          predicates:
            - Path=/api/v1/transactions/**
          filters:
            - Idempotency
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1

        - id: investment-service-route
          uri: http://bank-investment-service:8086
          predicates:
            - Path=/api/v1/investments/**
          filters:
            - Idempotency
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1


management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health, info, metrics
