server:
  port: 8082

spring:
  application:
    name: onboarding-service

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

zeebe:
  client:
    broker:
      gateway-address: 127.0.0.1:26500
    security:
      plaintext: true

resilience4j:
  retry:
    instances:
      kafkaRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.kafka.KafkaException

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics