server:
  port: 8086

spring:
  application:
    name: investment-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin@localhost:27017/bankhub_investments?authSource=admin}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://keycloak:8080/realms/bankhub/protocol/openid-connect/certs}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/bankhub}

bankhub:
  services:
    account:
      url: ${BANKHUB_SERVICES_ACCOUNT_URL:http://localhost:8081}

springdoc:
  swagger-ui:
    path: /swagger-ui.html


management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health, info, metrics
